import React from "react";
export default function Term() {
  return (
    <div className="container py-5">


       
      <div className="row">
        <div className="col-12">
        <h1 className="text-white  lll">TERM AND CONDITIONS</h1>
          <p className="text-white">
            The PridePixies is decentralized software running on the Polygon
            Matic network. This website is only an interface built to help users
            interact with the Polygon Matic smart contract, and the website’s
            account system is only used to send email notifications. No
            PridePixies ownership is managed by this website or by True Dream
            Vision LLC. Users are entirely responsible for the safety and
            management of their own private digital crypto wallets and
            validating all transactions generated by the website before
            approving them. Use of this website is at the user’s own risk and
            True Dream Vision LLC is not liable for any incorrect or failed
            transactions. Furthermore, as the contract runs on the Polygon Matic
            network, True Dream Vision LLC has no power to undo, reverse, or
            restore any transactions. In order to use this website, and any
            related tools it may provide, you agree to hold True Dream Vision
            LLC harmless for any and all problems, errors, and failures no
            matter the cause or source of those errors and accept sole
            responsibility for all transactions.
          </p>
        </div>
      </div>
      {/* <button type="button" id="hs_show_banner_button"
  style="background-color: #ff0ddb; border: 1px solid #ff0ddb;
         border-radius: 3px; padding: 10px 16px; text-decoration: none; color: #fff;
         font-family: inherit; font-size: inherit; font-weight: normal; line-height: inherit;
         text-align: left; text-shadow: none;"
  onClick="(function(){
    var _hsp = window._hsp = window._hsp || [];
    _hsp.push(['showBanner']);
  })()"
>
  Cookie Settings
</button> */}
    </div>
  );
}
